### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by mshodge** [OrdnanceSurvey/os-data-hub-api-tutorials#1]
Tried to run the tutorial on a Macbook Pro (32 GB 2400 MHz DDR4).

**Step 3** link 'Constructed OS Maps API URL' is not working.

```
Execution of Construct-Backend-URL-WMTS failed on line backendesriurl_js#94 with error: Unresolved variable : z
```

**Step 4** folium map does not load.

**Step 8** is very memory-heavy and caused kernel to crash and restart (did this three times in a row).

**Comment by steve-kingston** [comment]
Hi @mshodge ,

**Step 3 link 'Constructed OS Maps API URL' is not working.**

This exception is expected. The URL is designed to be passed to a web mapping library such as Leaflet. I’ve updated the notebook documentation to reflect this. See f3244c3143f54175b023c738d4ba79350b6173a4.

The z, y and x variables in the URL within Step 3 represent for an individual tile within the WMTS tile cache, the zoom level (z), tile row (y) and tile column (x) respectively.

The service expects integer values for the z, y and x variables to be provided in a request.

See the example request below:
https://osdatahubapi.os.uk/OSMapsAPI/wmts/v1?key=INSERT_API_KEY&service=wmts&version=2.0.0&request=GetTile&height=256&width=256&outputFormat=image/png&style=default&layer=Light_27700&tileMatrixSet=EPSG:27700&tileMatrix=EPSG:27700:2&tileRow=10&tileCol=10

Given the URL in Step 3, web mapping libraries are able to interpret the tiling scheme for the service and will trigger multiple requests with the required values for the z, y and x variables in order to get the collection of tiles necessary to fill the map extent.

**Step 4 folium map does not load.**

I can’t replicate this issue. Can you please check you have installed and imported the required dependencies and have inserted your own OS Data Hub API key?

**Step 8 is very memory-heavy and caused kernel to crash and restart (did this three times in a row).**

Testing using a Conda environment (Python 3.7 and GeoPandas 0.5) on Linux (Ubuntu) on a machine with 8GB RAM results in no issues. The Code-Point Open GeoPackage dataset is relatively small (~ 1.2 million rows) and occupies approximately 3.5GB in memory.

**Comment by mshodge** [comment]
Thanks @steve-kingston dependencies were causing me issues...

Step 4 now works. It was a probably with my version of folium, I was on 0.7.x - updating to the latest version (0.10.1) solved the problem. Maybe make a note of this in the documentation.

Step 8 also works. It may have been numpy, or another package, but basically I needed to reinstall my Anaconda and install packages back through conda and not pip. I read somewhere the pip version of numpy may have been to blame.

**Comment by steve-kingston** [comment]
@mshodge thanks for the feedback regarding Folium.

Glad to hear you've manged to fix the environment issues.
