### ISSUE TITLE
400 error TypeName has invalid value 'BoundaryLine_BoundaryLine'.

### ISSUE THREAD

**Issue by mshodge** [OrdnanceSurvey/os-data-hub-api-tutorials#2]
Hi again!

Just trying to re-run the notebook ahead of a session at the DSC in a few weeks.

Seems like there is an error with the BoundaryLine API calls.

I get the error:

`TypeName has invalid value 'BoundaryLine_BoundaryLine'.`

**Comment by steve-kingston** [comment]
Hi @mshodge,

Thanks for raising this. OS have withdrawn the Boundary Line product from the OS Features API due to technical issues. More information should be available via the notifications section of the OS Data Hub.

I've changed the LAD boundary WFS request in step 2 from the OS Data Hub OS Features API to the ONS Open Geography Portal WFS in order to fix this. Please see 8c967e09b133167815fa12899ef2d852ef629f70

Hope the session goes well.

Steve
